create table tb
(
num int primary key identity,
nam varchar(20),
product varchar(20)
)
insert into tb values('rk','test1')
insert into tb values('rk','test2')
insert into tb values('rk','test3')
insert into tb values('rk','test4')
insert into tb values('rk','test5')
insert into tb values('rk','test6')
insert into tb values('rk','test7')
insert into tb values('rk','test8')
insert into tb values('rk','test9')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')
insert into tb values('rk','test')


select * from tb
